// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
<<<<<<< HEAD
=======
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
>>>>>>> Martin
user_pref("app.normandy.user_id", "6fe45348-01e4-48bd-b923-f8a29efdd4e4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1637915392);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1637912353);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1637911888);
<<<<<<< HEAD
user_pref("app.update.lastUpdateTime.region-update-timer", 1637915632);
=======
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
>>>>>>> Martin
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1637912325);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1637912473);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1637915272);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1637912382);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1637915512);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1637911881);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 119);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7b1053fb-6ed8-4ab7-b621-930daf6d1b7e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1637911885);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1637912342356");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1637914127356");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1637911889520");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1637933489520");
user_pref("browser.search.region", "ES");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1637912329");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20211028161635");
user_pref("browser.startup.homepage_override.mstone", "94.0");
user_pref("browser.startup.lastColdStartupCheck", 1637912326);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1637911887593");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "94.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ES");
user_pref("dom.push.userAgentID", "97a0a0aaa69844e292b651784341883b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1637915393);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20211028161635");
user_pref("extensions.lastAppVersion", "94.0");
user_pref("extensions.lastPlatformVersion", "94.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.reset_default_search.runonce.3", true);
user_pref("extensions.reset_default_search.runonce.reason", "noAddonsEligible");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{a6b73a48-565f-468d-8fa2-e9fc92c31c0c}\",\"addons\":{\"addons-search-detection@mozilla.com\":{\"version\":\"1.0.1\"},\"reset-search-defaults@mozilla.com\":{\"version\":\"2.1.0\"}}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4c2dc138-2056-40d6-855a-dc4d6694b5ea\",\"formautofill@mozilla.org\":\"86e3c568-737b-4adb-8fe3-3003d35fad75\",\"pictureinpicture@mozilla.org\":\"9124e6af-7836-4365-994c-ccc7404b1758\",\"proxy-failover@mozilla.com\":\"d1d6a927-5277-4757-b1fa-56c7ad7028ba\",\"screenshots@mozilla.org\":\"a84e058e-0eea-45dd-aaf3-58a7f4b6d61d\",\"webcompat-reporter@mozilla.org\":\"7189a9d3-c5df-4b05-a52a-917b6b368db3\",\"webcompat@mozilla.org\":\"ff9c5cd1-192a-489e-a6ae-d286f283c092\",\"default-theme@mozilla.org\":\"ccd585a6-71ba-4cac-ad40-4c2bc7b8ebd5\",\"google@search.mozilla.org\":\"ad0a100c-2322-42de-a1b0-bc9f9e161381\",\"drae@search.mozilla.org\":\"d1ca5c58-0088-453e-9150-f1b62982af2e\",\"wikipedia@search.mozilla.org\":\"cd0e9797-a501-4c2d-afaf-befd969745fb\",\"bing@search.mozilla.org\":\"e39960b2-06fd-4d89-8efc-baa75d63321b\",\"ddg@search.mozilla.org\":\"e602ea28-ced2-4e85-a660-1ccdd350a052\",\"ebay@search.mozilla.org\":\"a0f58994-be01-42dd-9673-91e5ee833d02\",\"amazon@search.mozilla.org\":\"cd86ce04-6300-45d3-9160-533695719f37\",\"addons-search-detection@mozilla.com\":\"a56e7c1e-97ce-4daf-a23a-0b88f8c9014c\",\"reset-search-defaults@mozilla.com\":\"c643cd45-4f69-4948-94fa-afd03e46e544\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1637911888);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
<<<<<<< HEAD
user_pref("idle.lastDailyNotification", 1637915747);
=======
>>>>>>> Martin
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1637912402);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20211028161635");
user_pref("media.gmp-manager.lastCheck", 1637912402);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
<<<<<<< HEAD
user_pref("places.database.lastMaintenance", 1637915747);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1637915747927");
user_pref("privacy.sanitize.pending", "[]");
=======
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
>>>>>>> Martin
user_pref("security.remote_settings.crlite_filters.checked", 1637915081);
user_pref("security.remote_settings.intermediates.checked", 1637915081);
user_pref("security.sandbox.content.tempDirSuffix", "f16b8fd4-3a33-45ca-a3e8-7b23a5414724");
user_pref("services.blocklist.addons-mlbf.checked", 1637915081);
user_pref("services.blocklist.gfx.checked", 1637915081);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1637895625807\"");
user_pref("services.settings.last_update_seconds", 1637915272);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1637915081);
user_pref("services.settings.main.cfr.last_check", 1637915081);
user_pref("services.settings.main.doh-config.last_check", 1637915081);
user_pref("services.settings.main.doh-providers.last_check", 1637915081);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1637915081);
user_pref("services.settings.main.hijack-blocklists.last_check", 1637915081);
user_pref("services.settings.main.language-dictionaries.last_check", 1637915081);
user_pref("services.settings.main.message-groups.last_check", 1637915081);
user_pref("services.settings.main.nimbus-desktop-defaults.last_check", 1637915081);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1637915081);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1637915081);
user_pref("services.settings.main.partitioning-exempt-urls.last_check", 1637915081);
user_pref("services.settings.main.password-recipes.last_check", 1637915081);
user_pref("services.settings.main.password-rules.last_check", 1637915081);
user_pref("services.settings.main.pioneer-study-addons-v1.last_check", 1637915081);
user_pref("services.settings.main.public-suffix-list.last_check", 1637915081);
user_pref("services.settings.main.query-stripping.last_check", 1637915081);
user_pref("services.settings.main.search-config.last_check", 1637915081);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1637915081);
user_pref("services.settings.main.search-telemetry.last_check", 1637915081);
user_pref("services.settings.main.sites-classification.last_check", 1637915081);
user_pref("services.settings.main.top-sites.last_check", 1637915081);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1637915081);
user_pref("services.settings.main.websites-with-shared-credential-backends.last_check", 1637915081);
user_pref("services.settings.main.whats-new-panel.last_check", 1637915081);
user_pref("services.settings.security.onecrl.checked", 1637915081);
<<<<<<< HEAD
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1637915747);
=======
>>>>>>> Martin
user_pref("toolkit.startup.last_success", 1637912320);
user_pref("toolkit.telemetry.cachedClientID", "2511386d-dc48-4b60-920a-bbac7ab47a5a");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20211028161635");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
